services:
  use-url-query:
    user: 1000:1000
    image: oven/bun:1.3.5-slim
    command: [ "tail -f /dev/null" ]
    volumes:
      - ./:/srv/
    entrypoint: [ "sh", "-c" ]
    working_dir: /srv
    container_name: use-url-query  